### ISSUE TITLE
the installation work but status down

### ISSUE THREAD

**Issue by nslinux** [3m1o/nginx-rtmp-monitoring#7]
Hello
i installed the script and is working i goto the 9991 port is give me the script monitor but is not show any status all 0 and give me down and error msg Oh we have trouble! Please wait a little bit or contact technical support.

i edited the config file but same error 
{
  "site_title":"RTMP Monitoring",
  "http_server_port":9991,
  "rtmp_server_refresh":3000,
  "rtmp_server_timeout":15000,
  "rtmp_server_url":"http://localhost:9991/stat.xml",
  "rtmp_server_stream_url":"rtmp://localhost:9001/live/",
  "rtmp_server_control_url":"http://localhost:9991/control",
  "language":"en",
  "template":"default",
  "version":"1.0.0"
}

**Comment by fiftysoft** [comment]
change localhost with your server ip address , i think you don't need to add port try it without port and with port

**Comment by nishalpereira** [comment]
I have the same error. Changing localhost to server ip did not make any difference.
thanks again.

**Comment by fiftysoft** [comment]
@nslinux update the code now should be fixed

**Comment by Chinoman10** [comment]
@fiftysoft something happened to your commit, since people are still getting your old code.
I installed this today, using your own tutorial, and I got the 1.0.1 version instead of the fixed 1.0.2.

**Comment by Chinoman10** [comment]
@fiftysoft disregard my prev. comment (I'll delete it). Your commit didn't fix it though :/

**Comment by laddu38732** [comment]
I have the same error. Changing localhost to server ip did not make any difference. and I tried with a port number also no any difference same error. 
{
  "site_title":"RTMP Monitoring",
  "http_server_port":9991,
  "rtmp_server_refresh":3000,
  "rtmp_server_timeout":15000,
  "rtmp_server_url":"http://192.168.2.40/stat.xml",
  "rtmp_server_stream_url":"rtmp://192.168.2.40/live/",
  "rtmp_server_control_url":"http://192.168.2.40/control",
  "session_secret_key":"change_me_random",
  "language":"en",
  "template":"default",
  "login_template":"login",
  "version":"1.0.2"
}

**Comment by gavin2812** [comment]
I also have this same error, installation seems to work, but says server is down...

**Comment by ses27coves** [comment]
I also have this error. Over Ubuntu server 19.04

**Comment by jpossetti** [comment]
I had the same error, the problem was the http port. I have another http port instead 80, so, if is this your case, try to fix:
"rtmp_server_url":"http://[SERVER_IP]:[HTTP_PORT]/stat.xml",

**Comment by matigumma** [comment]
it was installed over docker?

**Comment by chrisspiegl** [comment]
I also have these issues.
Tested the stat URL, see the stuff there, also tested to CURL it and it worked…
Anybody found a way to get this working?

**Comment by 3m1o** [comment]
@chrisspiegl @matigumma @jpossetti  @ses27coves @gavin2812 @laddu38732 @Chinoman10 @nslinux 

maybe i can help you in twitter you or any other developers are welcome to send me a message and we can debug the issue i am 100% sure its simple issue about networking not the dashboard it self, 

https://twitter.com/3m1oo
